accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('', views.index, name='index'),
    path('products/', views.products, name='products'),
    path('customer/<int:pk>/', views.customer, name='customer'),
    path('create_order/', views.create_order, name='create_order'),
    path('update_order/<int:pk>/', views.update_order, name='update_order'),
    path('delete_order/<int:pk>/', views.delete_order, name='delete_order'),
    path('create_customer/', views.create_customer, name='create_customer'),
    path('update_customer/<int:pk>/',
         views.update_customer, name='update_customer'),
    path('delete_customer/<int:pk>/',
         views.delete_customer, name='delete_customer'),
    path('create_product/', views.create_product, name='create_product'),
    path('update_product/<int:pk>/', views.update_product, name='update_product'),
    path('delete_product/<int:pk>/', views.delete_product, name='delete_product'),
]

crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.


class Customer(models.Model):
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=10, null=True)
    email = models.EmailField(max_length=100, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    CATEGORY = (
        ('Indoor', 'Indoor'),
        ('Outdoor', 'Outdoor'),
    )
    name = models.CharField(max_length=200, null=True)
    price = models.FloatField(max_length=10, null=True)
    category = models.CharField(max_length=100, null=True, choices=CATEGORY)
    description = models.TextField(max_length=1000, null=True, blank=True)
    tags = models.ManyToManyField(Tag)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name


class Orders(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Out For Delivery', 'Out For Delivery'),
        ('Delivered', 'Delivered'),
    )
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    status = models.CharField(max_length=100, null=True, choices=STATUS)

    def __str__(self):
        return "Order Id: " + str(self.id) + " Product: " + str(self.product)

    class Meta:
        verbose_name_plural = 'Orders'
        verbose_name = 'Order'

accounts/forms.py
from django import forms
from django.forms import widgets
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class OrderForm(forms.ModelForm):

    class Meta:
        model = Orders
        fields = '__all__'
        widgets = {
            'customer': forms.Select(attrs={'class': 'form-control', 'id': 'name'}),
            'product': forms.Select(attrs={'class': 'form-control', 'id': 'product'}),
            'status': forms.Select(attrs={'class': 'form-control', 'id': 'status'})
        }


class CustomerForm(forms.ModelForm):

    class Meta:
        model = Customer
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'id': 'name', 'type': 'text'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'id': 'phone', 'type': 'phone'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'id': 'email', 'type': 'email'})
        }


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'id': 'name', 'type': 'text'}),
            'price': forms.TextInput(attrs={'class': 'form-control', 'id': 'price', 'type': 'number'}),
            'category': forms.Select(attrs={'class': 'form-control', 'id': 'category'}),
            'tags': forms.SelectMultiple(attrs={'class': 'form-control', 'id': 'tags'}),
        }


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'id': 'username', 'type': 'text'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'id': 'email', 'type': 'email'}),
        }

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *
from .filters import OrdersFilter
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def register(request):
    form = UserRegistrationForm()
    template = 'accounts/register.html'
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
    context = {
        'form': form,
    }
    return render(request, template, context)


def login(request):
    template = 'accounts/login.html'
    context = {}
    return render(request, template, context)


def index(request):
    orders = Orders.objects.all().order_by('-id')
    customers = Customer.objects.all()
    total_orders = orders.count()
    pending_orders = orders.filter(status='Pending').count()
    delivered_orders = orders.filter(status='Delivered').count()
    template = 'accounts/dashboard.html'
    context = {
        'orders': orders,
        'total_orders': total_orders,
        'pending_orders': pending_orders,
        'delivered_orders': delivered_orders,
        'customers': customers,
    }
    return render(request, template, context)


def products(request):
    products = Product.objects.all()
    template = 'accounts/products.html'
    context = {
        'products': products
    }
    return render(request, template, context)


def customer(request, pk):
    customer = Customer.objects.get(pk=pk)
    orders = customer.orders_set.all()
    myFilter = OrdersFilter(request.GET, queryset=orders)
    orders = myFilter.qs
    template = 'accounts/customer.html'
    context = {
        'customer': customer,
        'orders': orders,
        'myFilter': myFilter
    }
    return render(request, template, context)


def create_order(request):
    form = OrderForm()
    template = 'accounts/order_form.html'
    context = {
        'form': form
    }
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:index')

    return render(request, template, context)


def update_order(request, pk):
    order = Orders.objects.get(pk=pk)
    form = OrderForm(instance=order)
    template = 'accounts/order_form.html'
    context = {
        'form': form
    }
    if request.method == 'POST':
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            return redirect('accounts:index')
    return render(request, template, context)


def delete_order(request, pk):
    Orders.objects.get(pk=pk).delete()
    return redirect('accounts:index')


def create_customer(request):
    form = CustomerForm()
    template = 'accounts/customer_form.html'
    context = {
        'form': form
    }
    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:index')

    return render(request, template, context)


def update_customer(request, pk):
    customer = Customer.objects.get(pk=pk)
    form = CustomerForm(instance=customer)
    template = 'accounts/customer_form.html'
    context = {
        'form': form
    }
    if request.method == 'POST':
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            form.save()
            return redirect('accounts:index')
    return render(request, template, context)


def delete_customer(request, pk):
    Customer.objects.get(pk=pk).delete()
    return redirect('accounts:index')


def create_product(request):
    form = ProductForm()
    template = 'accounts/product_form.html'
    context = {
        'form': form
    }
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:products')

    return render(request, template, context)


def update_product(request, pk):
    product = Product.objects.get(pk=pk)
    form = ProductForm(instance=product)
    template = 'accounts/product_form.html'
    context = {
        'form': form
    }
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('accounts:products')
    return render(request, template, context)


def delete_product(request, pk):
    Product.objects.get(pk=pk).delete()
    return redirect('accounts:products')

accounts/templates/accounts/customer.html
{% extends 'base.html' %}{% block content %}
<div class="row">
  <div class="col-md">
    <div class="card card-body">
      <h5>Customer: {{ customer.name }}</h5>
      <hr />
      <a class="btn btn-outline-info btn-sm btn-block mb-2" href="{% url 'accounts:update_customer' customer.id %}"
        >Update Customer</a
      >
      <a class="btn btn-outline-danger btn-sm btn-block" href="{% url 'accounts:delete_customer' customer.id %}"
        >Delete Customer</a
      >
    </div>
  </div>

  <div class="col-md">
    <div class="card card-body">
      <h5>Contact Information</h5>
      <hr />
      <p>Email: {{ customer.email }}</p>
      <p>Phone: {{ customer.phone }}</p>
    </div>
  </div>

  <div class="col-md">
    <div class="card card-body">
      <h5>Total Orders</h5>
      <hr />
      <h1 style="text-align: center; padding: 10px">{{ orders.count }}</h1>
    </div>
  </div>
</div>

<br />
<div class="row">
  <div class="col">
    <div class="card card-body">
      <form method="get">
        {{ myFilter.form }}
        <button class="btn btn-primary" type="submit">Search</button>
      </form>
    </div>
  </div>
</div>
<br />

<div class="row">
  <div class="col-md">
    <div class="card card-body">
      <table class="table table-sm">
        <tr>
          <th>Product</th>
          <th>Category</th>
          <th>Date Orderd</th>
          <th>Status</th>
          <th>Update</th>
          <th>Remove</th>
        </tr>
        <tbody>
          {% for order in orders %}
          <tr>
            <td>{{ order.product.name }}</td>
            <td>{{ order.product.category }}</td>
            <td>{{ order.date_created }}</td>
            <td>{{ order.status }}</td>
            <td><a href="{% url 'accounts:update_order' order.id %}" class="btn btn-sm btn-outline-info">Update</a></td>
            <td
              ><a href="{% url 'accounts:delete_order' order.id %}" class="btn btn-sm btn-outline-danger">Remove</a></td
            >
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/customer_form.html
{% extends 'base.html' %}{% block content %}
<form method="post" action="">
  {% csrf_token %}
  <div class="form-row row">
    <div class="form-group col-md-3">
      <label for="name">Customer Name</label>
      {{ form.name }}
    </div>
    <div class="form-group col-md-3">
      <label for="phone">Phone</label>
      {{ form.phone }}
    </div>
    <div class="form-group col-md-3">
      <label for="email">E-mail</label>
      {{ form.email }}
    </div>
    <div class="form-group col-md-3">
      <button type="submit" class="btn btn-primary form-submit">Submit</button>
    </div>
  </div>
</form>
{% endblock %}

accounts/templates/accounts/dashboard.html
{% extends 'base.html' %}{% block content %} {% include 'accounts/status.html'%}
<div class="row mt-5" id="test">
  <div class="col-md-5">
    <h5>CUSTOMERS:</h5>
    <hr />
    <div class="card card-body">
      <a href="{% url 'accounts:create_customer' %}" class="btn btn-primary btn-sm btn-block">Create Customer</a>
      <table class="table table-sm">
        <tr>
          <th>Customer</th>
          <th>Phone</th>
          <th>Orders</th>
          <th></th>
        </tr>
        <tbody>
          {% for customer in customers %}
          <tr>
            <td>{{ customer.name }}</td>
            <td>{{ customer.phone }}</td>
            <td>{{ customer.orders_set.count }}</td>
            <td><a href="{% url 'accounts:customer' customer.id %}" class="btn btn-sm btn-outline-info">View</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-md-7">
    <h5>LAST 5 ORDERS:</h5>
    <hr />
    <div class="card card-body">
      <a href="{% url 'accounts:create_order' %}" class="btn btn-primary btn-sm btn-block">Create Order</a>
      <table class="table table-sm">
        <tr>
          <th>Product</th>
          <th>Date Ordered</th>
          <th>Status</th>
          <th>Update</th>
          <th>Remove</th>
        </tr>
        <tbody>
          {% for order in orders %}
          <tr>
            <td>{{ order.product.name }}</td>
            <td>{{ order.date_created }}</td>
            <td>{{ order.status }}</td>
            <td><a href="{% url 'accounts:update_order' order.id %}" class="btn btn-sm btn-outline-info">Update</a></td>
            <td><a href="{% url 'accounts:delete_order' order.id %}" class="btn btn-sm btn-outline-danger">Remove</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/login.html
<h3>Login</h3>

accounts/templates/accounts/order_form.html
{% extends 'base.html' %}{% block content %}
<form method="post" action="">
  {% csrf_token %}
  <div class="form-row row">
    <div class="form-group col-md-3">
      <label for="name">Customer Name</label>
      {{ form.customer }}
    </div>
    <div class="form-group col-md-3">
      <label for="phone">Product</label>
      {{ form.product }}
    </div>
    <div class="form-group col-md-3">
      <label for="email">Status</label>
      {{ form.status }}
    </div>
    <div class="form-group col-md-3">
      <button type="submit" class="btn btn-primary form-submit">Submit</button>
    </div>
  </div>
</form>
{% endblock %}

accounts/templates/accounts/product_form.html
{% extends 'base.html' %}{% block content %}
<form method="post" action="">
  {% csrf_token %}
  <div class="form-row row">
    <div class="form-group col-md-3">
      <label for="name">Product Name</label>
      {{ form.name }}
    </div>
    <div class="form-group col-md-3">
      <label for="price">Price</label>
      {{ form.price }}
    </div>
    <div class="form-group col-md-3">
      <label for="category">Category</label>
      {{ form.category }}
    </div>
    <div class="form-group col-md-3">
      <label for="tags">Tags</label>
      {{ form.tags }}
    </div>
    <div class="form-group col-md-3">
      <button type="submit" class="btn btn-primary form-submit">Submit</button>
    </div>
  </div>
</form>
{% endblock %}

accounts/templates/accounts/products.html
{% extends 'base.html' %}{% block content %}
<div class="row">
  <div class="col-md">
    <div class="card card-body">
      <h5>Products</h5>
    </div>
    <div class="card card-body">
      <a href="{% url 'accounts:create_product' %}" class="btn btn-primary btn-sm btn-block">Create Product</a>
      <table class="table">
        <tr>
          <th>Product</th>
          <th>Category</th>
          <th>Price</th>
          <th>Update</th>
          <th>Remove</th>
        </tr>
        <tbody>
          {% for product in products %}
          <tr>
            <td>{{ product.name }}</td>
            <td>{{ product.category }}</td>
            <td>{{ product.price }}</td>
            <td
              ><a href="{% url 'accounts:update_product' product.id %}" class="btn btn-sm btn-outline-info"
                >Update</a
              ></td
            >
            <td
              ><a href="{% url 'accounts:delete_product' product.id %}" class="btn btn-sm btn-outline-danger"
                >Remove</a
              ></td
            >
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}{% block content %}
<form method="post" action="">
  {% csrf_token %}
  <div id="login">
    <div class="container">
      <div id="login-row" class="row justify-content-center align-items-center">
        <div id="login-column" class="col-md-6">
          <div id="login-box" class="col-md-12">
            <form id="login-form" class="form" action="" method="post">
              <h3 class="text-center text-info">Register</h3>
              <div class="form-group">
                <label for="username" class="text-info">{{form.username.label}}:</label><br />
                {{form.username}}
              </div>
              <div class="form-group">
                <label for="username" class="text-info">{{form.email.label}}:</label><br />
                {{form.email}}
              </div>
              <div class="form-group">
                <label for="password1" class="text-info">{{form.password1.label}}:</label><br />
                {{form.password1}}
              </div>
              <div class="form-group">
                <label for="password2" class="text-info">{{form.password2.label}}:</label><br />
                {{form.password2}}
              </div>
              <div class="form-group mt-5">
                <input type="submit" name="submit" class="btn btn-primary btn-md" value="submit" />
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}

accounts/templates/accounts/status.html
<div class="row">
  <div class="col">
    <div class="col-md">
      <div class="card text-center text-white mb-3" id="total-orders">
        <div class="card-header">
          <h5 class="card-title">Total Orders</h5>
        </div>
        <div class="card-body">
          <h3 class="card-title">{{ total_orders }}</h3>
        </div>
      </div>
    </div>
  </div>

  <div class="col">
    <div class="col-md">
      <div class="card text-center text-white mb-3" id="orders-delivered">
        <div class="card-header">
          <h5 class="card-title">Orders Delivered</h5>
        </div>
        <div class="card-body">
          <h3 class="card-title">{{ delivered_orders }}</h3>
        </div>
      </div>
    </div>
  </div>

  <div class="col">
    <div class="col-md">
      <div class="card text-center text-white mb-3" id="orders-pending">
        <div class="card-header">
          <h5 class="card-title">Orders Pending</h5>
        </div>
        <div class="card-body">
          <h3 class="card-title">{{ pending_orders }}</h3>
        </div>
      </div>
    </div>
  </div>
</div>